services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgres/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres:
    driver: bridge